### ISSUE TITLE
About Inference Code

### ISSUE THREAD

**Issue by YuHuiGao** [yeliudev/VideoMind#4]
Hello, do you have any code for running VideoMind inference on multiple GPUs? After I tried modifying the code, it showed an error requiring the model to be loaded on the same device. My setup consists of four 24GB 3090 GPUs. Whether I try to run VideoMind-2B or VideoMind-7B, it often runs out of memory (OOM) when attempting inference on a single 3090 GPU. I want to compare the inference capabilities of VideoMind and Qwen2-VL.

**Comment by yeliudev** [comment]
Hi @YuHuiGao, we've pushed the commit to support multi-device inference. Please pull the latest code and try the following script for your case. The key is to set `--device all` when running `videomind/eval/infer_auto.py`.

```shell
#!/bin/bash

set -e

export CUDA_VISIBLE_DEVICES=0,1,2,3
export ASCEND_RT_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
export PYTHONPATH="./:$PYTHONPATH"

dataset=$1
split=${2:-"test"}

model_gnd_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"
model_ver_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"
model_pla_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"

pred_path="outputs/${dataset}_${split}"

echo -e "\e[1;36mEvaluating:\e[0m $dataset ($split)"

python videomind/eval/infer_auto.py \
    --dataset $dataset \
    --split $split \
    --pred_path $pred_path \
    --model_gnd_path $model_gnd_path \
    --model_ver_path $model_ver_path \
    --model_pla_path $model_pla_path \
    --device all

python videomind/eval/eval_auto.py $pred_path --dataset $dataset

```

**Comment by fake-warrior8** [comment]
> Hi [@YuHuiGao](https://github.com/YuHuiGao), we've pushed the commit to support multi-device inference. Please pull the latest code and try the following script for your case. The key is to set `--device all` when running `videomind/eval/infer_auto.py`.
> 
> #!/bin/bash
> 
> set -e
> 
> export CUDA_VISIBLE_DEVICES=0,1,2,3
> export ASCEND_RT_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
> export PYTHONPATH="./:$PYTHONPATH"
> 
> dataset=$1
> split=${2:-"test"}
> 
> model_gnd_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"
> model_ver_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"
> model_pla_path="model_zoo/VideoMind-2B"  # or "model_zoo/VideoMind-7B"
> 
> pred_path="outputs/${dataset}_${split}"
> 
> echo -e "\e[1;36mEvaluating:\e[0m $dataset ($split)"
> 
> python videomind/eval/infer_auto.py \
>     --dataset $dataset \
>     --split $split \
>     --pred_path $pred_path \
>     --model_gnd_path $model_gnd_path \
>     --model_ver_path $model_ver_path \
>     --model_pla_path $model_pla_path \
>     --device all
> 
> python videomind/eval/eval_auto.py $pred_path --dataset $dataset

When using "--device all", I also meet the device bugs for 8-gpu inference:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:1! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

**Comment by yeliudev** [comment]
Could you please confirm that you are using the lastest code?

**Comment by fake-warrior8** [comment]
> Could you please confirm that you are using the lastest code?

I git clone the code about 1 hour ago

**Comment by yeliudev** [comment]
Could you provide the full error log? I tried 8 GPUs (V100 32G) before but didn't meet this issue.

**Comment by yeliudev** [comment]
Generally, to fix this kind of error, the specific tensor shall be manually moved to the target device during inference.

Or you could simply try using fewer GPUs and see whether the partition problem still exists.

**Comment by fake-warrior8** [comment]
> Could you provide the full error log? I tried 8 GPUs (V100 32G) before but didn't meet this issue.
Generally, to fix this kind of error, the specific tensor shall be manually moved to the target device during inference.

Or you could simply try using fewer GPUs and see whether the partition problem still exists.


I ran on A100 with 8 gpus. I can run the inference with your eval_auto.sh (8 launch). But I will meet the device errors when using 8 gpus/4 gpus.

**Comment by yeliudev** [comment]
It seems like a bug in huggingface. For a quick fix, you may try going into the transformers package in your conda env and modifying [this line](https://github.com/huggingface/transformers/blob/v4.45.2/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1719) by manually moving hidden_states to the device of lm_head before it. I'll investigate this issue further and see if it can be fixed without modifying transformers.

**Comment by fake-warrior8** [comment]
> It seems like a bug in huggingface. For a quick fix, you may try going into the transformers package in your conda env and modifying [this line](https://github.com/huggingface/transformers/blob/v4.45.2/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1719) by manually moving hidden_states to the device of lm_head before it. I'll investigate this issue further and see if it can be fixed without modifying transformers.

Thank you for give the code link. I may know the bugs.. I loaded the ckpt of qwenvl2.5 but not qwenvl2.

**Comment by yeliudev** [comment]
I see. Glad to hear that the problem is solved. 😂

**Comment by fake-warrior8** [comment]
> I see. Glad to hear that the problem is solved. 😂


> It seems like a bug in huggingface. For a quick fix, you may try going into the transformers package in your conda env and modifying [this line](https://github.com/huggingface/transformers/blob/v4.45.2/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1719) by manually moving hidden_states to the device of lm_head before it. I'll investigate this issue further and see if it can be fixed without modifying transformers.

I replaced the qwenvl2.5 with qwenvl2 and changed the line you gave. It did not work.

**Comment by yeliudev** [comment]
What's the error log now?

**Comment by fake-warrior8** [comment]
> What's the error log now?

Keep the same as the previous: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:1! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

**Comment by fake-warrior8** [comment]
> I see. Glad to hear that the problem is solved. 😂

I use the eval_auto_7b.sh script and test on the Charades dataset. The result is as follows, the mIoU is 29.2, which is far lower than the reported 50.2:


[nan, nan, nan, nan, nan]
[0, 1, 2, 3, 4]
[0.0, 9.954733004847174] [[16.5, 28.0]] 29.864199014541523

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 465/465, 0.1 task/s, elapsed: 1h53m28s, eta: 0s
CG-Bench mode: False
Total number of files: 8

Grounding (IoU):
+---------+----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+
| Task    | #Samples | Failed | R1@0.3 | R1@0.5 | R1@0.7 | R3@0.3 | R3@0.5 | R3@0.7 | R5@0.3 | R5@0.5 | R5@0.7 | mIoU  |
+---------+----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+
| unknown | 3720     | 3720   | 42.96  | 30.40  | 17.31  | 69.73  | 56.53  | 29.33  | 98.33  | 85.19  | 44.44  | 29.19 |
| all     | 3720     | 3720   | 42.96  | 30.40  | 17.31  | 69.73  | 56.53  | 29.33  | 98.33  | 85.19  | 44.44  | 29.19 |
+---------+----------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+-------+

**Comment by yeliudev** [comment]
```
[nan, nan, nan, nan, nan]
[0, 1, 2, 3, 4]
[0.0, 9.954733004847174] [[16.5, 28.0]] 29.864199014541523
```

Did you modified any part of the code?

**Comment by fake-warrior8** [comment]
> ```
> [nan, nan, nan, nan, nan]
> [0, 1, 2, 3, 4]
> [0.0, 9.954733004847174] [[16.5, 28.0]] 29.864199014541523
> ```
> 
> Did you modified any part of the code?

I only changed the model_path and video_root_path.

**Comment by yeliudev** [comment]
But why does it print these unexpected NaNs and numbers?

**Comment by fake-warrior8** [comment]
> But why does it print these unexpected NaNs and numbers?

Here is the prediction example in the output_0.json:

    {
        "source": "charades_sta",
        "data_type": "grounding",
        "video_path": "data/charades_sta/videos_3fps_480_noaudio/V7YEJ.mp4",
        "duration": 30.966666666666665,
        "query": "person begins eating",
        "span": [
            [
                9.9,
                16.9
            ]
        ],
        "agents": [
            "grounder",
            "verifier"
        ],
        "grounder_response": "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "grounder_success": false,
        "pred": [
            [
                0.0,
                10.322222222222221
            ],
            [
                5.1611111111111105,
                15.483333333333333
            ],
            [
                10.322222222222221,
                20.644444444444442
            ],
            [
                15.483333333333333,
                25.805555555555554
            ],
            [
                20.644444444444442,
                30.966666666666665
            ]
        ],
        "conf": [
            0,
            0,
            0,
            0,
            0
        ],
        "probs": [NaN, NaN, NaN, NaN, NaN
        ],
        "ranks": [
            0,
            1,
            2,
            3,
            4
        ],
        "pred_ori": [
            [
                0.0,
                10.322222222222221
            ],
            [
                5.1611111111111105,
                15.483333333333333
            ],
            [
                10.322222222222221,
                20.644444444444442
            ],
            [
                15.483333333333333,
                25.805555555555554
            ],
            [
                20.644444444444442,
                30.966666666666665
            ]
        ],
        "conf_ori": [
            0,
            0,
            0,
            0,
            0
        ]
    },

**Comment by yeliudev** [comment]
The `grounder_response` is not outputting as expected. I guess it is still the checkpoint issue. Please double-check that you are using the correct checkpoint for VideoMind-7B.

**Comment by fake-warrior8** [comment]
> The `grounder_response` is not outputting as expected. I guess it is still the checkpoint issue. Please double-check that you are using the correct checkpoint for VideoMind-7B.

I load the wrong ckpt of qwen2 but not qwenvl-2.. Finally, I get the paper's similar result (My mIoU is 50.4, the paper reported 50.2).
I still have a problem, why test using [the top-1 prediction without confidence](https://github.com/yeliudev/VideoMind/blob/47ef9e85e02fe91585df1a2d8015f10af5f6670a/videomind/eval/eval_auto.py#L127)?
I find that when using the confidence, the result is much worse and is merely the same as the first grounding result.
W confidence, mIoU=50.4
W.o confidence, mIoU=48.2

**Comment by yeliudev** [comment]
What do you mean by using confidence? It that mean applying a `verifier` after `grounder`?

**Comment by fake-warrior8** [comment]
It means applying a verifier after grounder and sorted the top k prediction using confidence (dump['conf']).  I find that the verifier already sort these results and the dum['conf'] is only a copy of the confidence of grounder. So w. confidence, the final result is the same as the result of gounder.

**Comment by yeliudev** [comment]
Yes, your understanding is correct.
